/* MENUGET_MENU */
export const GET_MENU = "GET_MENU"
export const GET_MENU_SUCCESS = "GET_MENU_SUCCESS"
export const GET_MENU_FAIL = "GET_MENU_FAIL"

export const POST_ADD_MENU = "POST_ADD_MENU"
export const POST_ADD_MENU_SUCCESS = "POST_ADD_MENU_SUCCESS"
export const POST_ADD_MENU_FAIL = "POST_ADD_MENU_FAIL"

export const PUT_UPDATE_MENU = "PUT_UPDATE_MENU"
export const PUT_UPDATE_MENU_SUCCESS = "PUT_UPDATE_MENU_SUCCESS"
export const PUT_UPDATE_MENU_FAIL = "PUT_UPDATE_MENU_FAIL"


